version: '3.8'

services:
  django:
    build: ./django
    # command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    expose:
      - 8000
    volumes:
      - ./src:/code
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/collected_static:/static
    depends_on:
      - django
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres-data: